### ISSUE TITLE
Style transfer code

### ISSUE THREAD

**Issue by LHRYANG** [dykang/PASTEL#4]
Hi, I think the style transfer code is a machine translation code.  Do you upload the wrong files or I make some mistakes since I do not read the whole code.

**Comment by vgtomahawk** [comment]
The style transfer code indeed does use a (often used in machine translation) style sequence to sequence model, with dot product attention and LSTMs as encoder and decoder respectively. Since we had parallel data [supervised style transfer], our problem is essentially a sequence transduction problem [i.e Seq2Seq], i.e Source Sentence, Target Style --> Target Sentence . We incorporated target style in the form of special tokens at the start of source sentence input tokens.

Are there any specific issues/problems you are facing with running the code? If there are, please let us know where [Or was your question just from a theoretical point of view? ]

**Comment by LHRYANG** [comment]
Thanks for you quick response, actually, I have not run the code and I am reading the code. I will
